/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.threesister.views;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import com.threesister.DAO.AddStaff;
import com.threesister.dbmanager.DbManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author biswas
 */
public class AddTrekkingStaff extends javax.swing.JFrame {

    /**
     * Creates new form AddTrekkingStaff
     */
    public AddTrekkingStaff() {
        initComponents();
        JComboBox staffType = new JComboBox();
        FillCombo();
        showStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        staffName = new javax.swing.JTextField();
        staffType = new javax.swing.JComboBox<>();
        addTrekkingStaff = new javax.swing.JButton();
        updateStaff = new javax.swing.JButton();
        deleteStaff = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        staffId = new javax.swing.JTextField();
        licenseNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mobileNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffListTable = new javax.swing.JTable();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Post");

        staffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffNameActionPerformed(evt);
            }
        });

        staffType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffTypeActionPerformed(evt);
            }
        });

        addTrekkingStaff.setText("Add");
        addTrekkingStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrekkingStaffActionPerformed(evt);
            }
        });

        updateStaff.setText("Update");
        updateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStaffActionPerformed(evt);
            }
        });

        deleteStaff.setText("Delete");
        deleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStaffActionPerformed(evt);
            }
        });

        jLabel3.setText("Id");

        jLabel4.setText("License No");

        jLabel5.setText("Mobile No");

        jLabel6.setText("Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(staffName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffId, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addTrekkingStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staffType, 0, 168, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(licenseNo)
                            .addComponent(mobileNo)
                            .addComponent(address))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(staffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(staffType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(licenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTrekkingStaff)
                    .addComponent(updateStaff)
                    .addComponent(deleteStaff))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        staffListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.N", "Staff Name", "Post", "License No", "Mobile No", "Address", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staffListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(staffListTable);

        close.setText("close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(361, 361, 361))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffTypeActionPerformed

    private void staffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffNameActionPerformed

    private void addTrekkingStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrekkingStaffActionPerformed
        // TODO add your handling code here:
        String name = staffName.getText();
        String post = (String) staffType.getSelectedItem();
        String licenseNo = this.licenseNo.getText();
        String mobileNo = this.mobileNo.getText();
        String address = this.address.getText();
        if ((!"".equals(name) || name != null)
                && (!"".equals(post) || post != null)
                && (!"".equals(mobileNo) || mobileNo != null)
                && (!"".equals(address) || address != null)) {
            boolean isAdded = AddStaff.addStaff(name, post, licenseNo, mobileNo, address);
            if (isAdded) {
                DefaultTableModel model = (DefaultTableModel) staffListTable.getModel();
                model.setRowCount(0);
                showStaff();
                JOptionPane.showMessageDialog(null, "Staff added Sucessfully");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please provide details");
        }
    }//GEN-LAST:event_addTrekkingStaffActionPerformed

    private void updateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStaffActionPerformed

        int row = staffListTable.getSelectedRow();
        int id = (int) (staffListTable.getModel().getValueAt(row, 3));
        try {
            Connection con = null;
            ResultSet rs = null;
            PreparedStatement ps = null;
            String sql = "update Staff set StaffName=?, Post=?, LicenseNo=?, MobileNo=?, Address=? where id='" + id + "'";

            System.out.println(sql);
            con = DbManager.getConnection();
            ps = con.prepareStatement(sql);
            ps.setString(1, staffName.getText());

            String post;
            post = staffType.getSelectedItem().toString();
            ps.setString(2, post);
            ps.setString(3, licenseNo.getText());
            ps.setString(4, mobileNo.getText());
            ps.setString(5, address.getText());
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) staffListTable.getModel();
            model.setRowCount(0);
            showStaff();
            JOptionPane.showMessageDialog(null, "Staff updated Sucessfully");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateStaffActionPerformed

    private void staffListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffListTableMouseClicked
        int i = staffListTable.getSelectedRow();

        TableModel model = staffListTable.getModel();
        staffName.setText(model.getValueAt(i, 1).toString());
        String post = model.getValueAt(i, 2).toString();
        switch (post) {
            case "Guide":
                staffType.setSelectedIndex(0);
                break;
            case "Assistant Guide":
                staffType.setSelectedIndex(1);
                break;
            case "Assistant":
                staffType.setSelectedIndex(2);
                break;
        }
        licenseNo.setText(model.getValueAt(i, 3).toString());
        mobileNo.setText(model.getValueAt(i, 4).toString());
        address.setText(model.getValueAt(i, 5).toString());
        staffId.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_staffListTableMouseClicked

    private void deleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStaffActionPerformed
        int row = staffListTable.getSelectedRow();
        int id = (int) (staffListTable.getModel().getValueAt(row, 3));
        try {
            Connection con = null;
            ResultSet rs = null;
            PreparedStatement ps = null;
            String sql = "update Staff set Deleted='Y' where id='" + id + "'";

            con = DbManager.getConnection();
            ps = con.prepareStatement(sql);
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) staffListTable.getModel();
            model.setRowCount(0);
            showStaff();
            JOptionPane.showMessageDialog(null, "Staff Deleted Sucessfully");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteStaffActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    public void FillCombo() {
        staffType.addItem("Guide");
        staffType.addItem("Assistant Guide");
        staffType.addItem("Assistant");
    }

    public ArrayList<Staff> staffList() {
        ArrayList<Staff> staffList = new ArrayList<>();
        try {
            Connection con = null;
            ResultSet rs = null;
            PreparedStatement ps = null;

            String sql = "select * from Staff where Deleted='N'";

            con = DbManager.getConnection();
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            Staff staff;
            while (rs.next()) {
                staff = new Staff(rs.getInt("id"), rs.getString("StaffName"),
                        rs.getString("Post"),
                        rs.getString("LicenseNo"),
                        rs.getString("MobileNo"),
                        rs.getString("Address"));
                staffList.add(staff);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return staffList;
    }

    public void showStaff() {
        ArrayList<Staff> list = staffList();
        DefaultTableModel model = (DefaultTableModel) staffListTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        staffListTable.setDefaultRenderer(String.class, centerRenderer);
        int sn = 1;
        for (int i = 0; i < list.size(); i++) {
            Object[] row = new Object[7];
            row[0] = sn++;
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getPost();
            row[3] = list.get(i).getLicenseNo();
            row[4] = list.get(i).getMobileNo();
            row[5] = list.get(i).getAddress();
            row[6] = list.get(i).getId();
            model.addRow(row);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTrekkingStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTrekkingStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTrekkingStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTrekkingStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTrekkingStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTrekkingStaff;
    private javax.swing.JTextField address;
    private javax.swing.JButton close;
    private javax.swing.JButton deleteStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField licenseNo;
    private javax.swing.JTextField mobileNo;
    private javax.swing.JTextField staffId;
    private javax.swing.JTable staffListTable;
    private javax.swing.JTextField staffName;
    private javax.swing.JComboBox<String> staffType;
    private javax.swing.JButton updateStaff;
    // End of variables declaration//GEN-END:variables
}
