/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.threesister.views;

import com.threesister.DAO.AddBusTicketDAO;
import com.threesister.dbmanager.DbManager;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author biswas
 */
public class ManageBus extends javax.swing.JFrame {

    /**
     * Creates new form ManageBus
     */
    public ManageBus() {
        initComponents();
        showBusInfoList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        busName = new javax.swing.JTextField();
        travelAgencyName = new javax.swing.JTextField();
        ticketNumber = new javax.swing.JTextField();
        addBusTicket = new javax.swing.JButton();
        updateBusTicket = new javax.swing.JButton();
        deleteBusTicket = new javax.swing.JButton();
        issueDateChooser = new com.toedter.calendar.JDateChooser();
        departureDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        busInfoListTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Id");

        jLabel3.setText("Name");

        jLabel4.setText("Travel Agency");

        jLabel5.setText("Date Of Issue");

        jLabel6.setText("Departure Date");

        jLabel7.setText("Ticket Number");

        id.setEditable(false);

        addBusTicket.setText("ADD");
        addBusTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusTicketActionPerformed(evt);
            }
        });

        updateBusTicket.setText("UPDATE");
        updateBusTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBusTicketActionPerformed(evt);
            }
        });

        deleteBusTicket.setText("DELETE");
        deleteBusTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBusTicketActionPerformed(evt);
            }
        });

        issueDateChooser.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBusTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBusTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBusTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(busName)
                            .addComponent(id)
                            .addComponent(travelAgencyName)
                            .addComponent(ticketNumber)
                            .addComponent(issueDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departureDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(busName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(travelAgencyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(issueDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(departureDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ticketNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBusTicket)
                    .addComponent(updateBusTicket)
                    .addComponent(deleteBusTicket))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        busInfoListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sn", "Name", "Travel Agency", "Issue Date", "Departure Date", "Ticket Number", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        busInfoListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busInfoListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(busInfoListTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBusTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusTicketActionPerformed
        String name = busName.getText();
        String travelAgency = travelAgencyName.getText();
        String issueDate = ((JTextField) issueDateChooser.getDateEditor().getUiComponent()).getText();
        String departureDate = ((JTextField) departureDateChooser.getDateEditor().getUiComponent()).getText();
        String ticketNumber = this.ticketNumber.getText();
        if (!"".equals(name) && !"".equals(travelAgency) && !"".equals(issueDate) && !"".equals(departureDate) && !"".equals(ticketNumber)) {
            try {
                boolean isAdded = AddBusTicketDAO.addBusTicket(name, travelAgency, issueDate, departureDate, ticketNumber);
                if (isAdded) {
                    DefaultTableModel model = (DefaultTableModel) busInfoListTable.getModel();
                    model.setRowCount(0);
                    showBusInfoList();
                    JOptionPane.showMessageDialog(null, "Bus info added sucessfully");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please provide all the necessary details");
        }
    }//GEN-LAST:event_addBusTicketActionPerformed

    private void busInfoListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busInfoListTableMouseClicked
        int i = busInfoListTable.getSelectedRow();

        TableModel model = busInfoListTable.getModel();
        busName.setText(model.getValueAt(i, 1).toString());
        travelAgencyName.setText(model.getValueAt(i, 2).toString());
        try {
            java.util.Date issueDate = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(i, 3));
            issueDateChooser.setDate(issueDate);
            java.util.Date departureDate = new SimpleDateFormat("MMM d, yyyy").parse((String) model.getValueAt(i, 4));
            departureDateChooser.setDate(departureDate);
        } catch (ParseException ex) {
            Logger.getLogger(ManageBus.class.getName()).log(Level.SEVERE, null, ex);
        }
        ticketNumber.setText(model.getValueAt(i, 5).toString());
        id.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_busInfoListTableMouseClicked

    private void updateBusTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBusTicketActionPerformed
        int row = busInfoListTable.getSelectedRow();
        int id = (int) (busInfoListTable.getModel().getValueAt(row, 6));
        String issueDate = ((JTextField) issueDateChooser.getDateEditor().getUiComponent()).getText();
        String departureDate = ((JTextField) departureDateChooser.getDateEditor().getUiComponent()).getText();
        try {
            Connection con = null;
            ResultSet rs = null;
            PreparedStatement ps = null;
            String sql = "update BusTicket set Name=?, TravelAgency=?, IssueDate=?, DepartureDate=?,TicketNumber=?  where id='" + id + "'";

            System.out.println(sql);
            con = DbManager.getConnection();
            ps = con.prepareStatement(sql);
            ps.setString(1, busName.getText());
            ps.setString(2, travelAgencyName.getText());
            ps.setString(3, issueDate);
            ps.setString(4, departureDate);
            ps.setString(5, ticketNumber.getText());
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) busInfoListTable.getModel();
            model.setRowCount(0);
            showBusInfoList();
            JOptionPane.showMessageDialog(null, "Bus info updated Sucessfully");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateBusTicketActionPerformed

    private void deleteBusTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBusTicketActionPerformed
        int row = busInfoListTable.getSelectedRow();
        int id = (int) (busInfoListTable.getModel().getValueAt(row, 5));
        try {
            Connection con = null;
            ResultSet rs = null;
            PreparedStatement ps = null;
            String sql = "update BusTicket set Deleted='Y' where id='" + id + "'";

            con = DbManager.getConnection();
            ps = con.prepareStatement(sql);
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) busInfoListTable.getModel();
            model.setRowCount(0);
            showBusInfoList();
            JOptionPane.showMessageDialog(null, "Staff Deleted Sucessfully");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteBusTicketActionPerformed

    public ArrayList<BusTicket> busInfoList() {
        ArrayList<BusTicket> busTicketlList = new ArrayList<>();
        try {
            Connection con = null;
            ResultSet rs = null;
            PreparedStatement ps = null;

            String sql = "select * from BusTicket where Deleted='N'";

            con = DbManager.getConnection();
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            BusTicket busTicket = null;
            while (rs.next()) {
                busTicket = new BusTicket(rs.getInt("ID"),
                        rs.getString("Name"),
                        rs.getString("TravelAgency"),
                        rs.getString("IssueDate"),
                        rs.getString("DepartureDate"),
                        rs.getString("TicketNumber"));
                busTicketlList.add(busTicket);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return busTicketlList;
    }

    public void showBusInfoList() {
        ArrayList<BusTicket> list = busInfoList();
        DefaultTableModel model = (DefaultTableModel) busInfoListTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        busInfoListTable.setDefaultRenderer(String.class, centerRenderer);
        int sn = 1;
        for (int i = 0; i < list.size(); i++) {
            Object[] row = new Object[7];
            row[0] = sn++;
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getTravelAgency();
            row[3] = list.get(i).getIssueDate();
            row[4] = list.get(i).getDepartureDate();
            row[5] = list.get(i).getTicketNumber();
            row[6] = list.get(i).getId();
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBusTicket;
    private javax.swing.JTable busInfoListTable;
    private javax.swing.JTextField busName;
    private javax.swing.JButton deleteBusTicket;
    private com.toedter.calendar.JDateChooser departureDateChooser;
    private javax.swing.JTextField id;
    private com.toedter.calendar.JDateChooser issueDateChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ticketNumber;
    private javax.swing.JTextField travelAgencyName;
    private javax.swing.JButton updateBusTicket;
    // End of variables declaration//GEN-END:variables
}
